name: Build Website
on:
  pull_request:
  push:
    branches:
      - master
      - dev

env:
  NUM_WORKERS: 15

jobs:
  cancel:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

  matrix:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Generate Build Matrix
        id: matrix
        run: |
          echo "::set-output name=matrix::$(python3 .github/workflows/github_job_scheduler.py \
            build-matrix \
            ${{ github.workspace }} \
            --num-workers=${{ env.NUM_WORKERS }})"
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

  build:
    runs-on: ubuntu-20.04
    needs:
      - cancel
      - matrix
    strategy:
      matrix:
        offset: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set Matrix offset file
        run: |
          cat >matrix_info.txt <<EOL
          workers: ${{ env.NUM_WORKERS }}
          offset: ${{ matrix.offset }}
          EOL

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
          cache: pip
          cache-dependency-path: |
            matrix_info.txt
            requirements.txt
            requirements_no_deps.txt

      - name: Install OS build dependencies
        run: |
          sudo apt-get install -y pandoc -qq

      - name: Install pip dependencies
        run: |
          pip install pip setuptools cmake --upgrade
          pip install -r requirements.txt
          pip install --no-deps -r requirements_no_deps.txt

      - name: Execute Matrix offset
        run: |
          python3 .github/workflows/github_job_scheduler.py \
           execute-matrix \
           ${{ github.workspace }} \
           --num-workers=${{ env.NUM_WORKERS }} \
           --offset=${{ matrix.offset }} \
           --verbose

      - name: Gallery Cache (on Pull Request)
        if: github.event_name == 'pull_request'
        uses: actions/cache@v3
        with:
          path: demos
          key: gallery-v34a-${{ matrix.offset }}-${{ env.NUM_WORKERS }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            gallery-v34a-${{ matrix.offset }}-${{ env.NUM_WORKERS }}-${{ github.ref_name }}-
            gallery-v34a-${{ matrix.offset }}-${{ env.NUM_WORKERS }}-
            gallery-v34a-

      - name: Gallery Cache (on Push to default branches)
        if: github.event_name == 'push'
        uses: actions/cache@v3
        with:
          path: demos
          key: gallery-v34a-${{ matrix.offset }}-${{ env.NUM_WORKERS }}-

      - name: Build Tutorials
        run: |
          make download
          make html

      - name: Clean HTML Files
        run: |
          python3 .github/workflows/github_job_scheduler.py \
           clean-html \
           ${{ github.workspace }} \
           --num-workers=${{ env.NUM_WORKERS }} \
           --offset=${{ matrix.offset }} \
           --verbose

      - name: Upload QML Demos
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: qml_demos-${{ matrix.offset }}.zip
          path: demos
          retention-days: 1

      - name: Upload QML Backreferences
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: qml_backreferences-${{ matrix.offset }}.zip
          path: backreferences
          if-no-files-found: ignore
          retention-days: 1

      - name: Upload Html
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: html-${{ matrix.offset }}.zip
          path: _build/html
          if-no-files-found: error
          retention-days: 1

      - name: Upload Results
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.offset }}.zip
          path: _build/test-results
          retention-days: 1

      # These two steps are required as the subsequent workflow_run will not have
      #  the current context available to it.
      - name: Save PR Number
        if: github.event_name == 'pull_request' && matrix.offset == 1
        run: |
          mkdir -p /tmp/pr
          cat >/tmp/pr/pr_info.json <<EOL
          {
            "id": "${{ github.event.pull_request.number }}",
            "title": "${{ github.event.pull_request.title }}",
            "author": "${{ github.event.pull_request.user.login }}",
            "ref": "${{ github.sha }}",
            "ref_name": "${{ github.ref_name }}"
          }
          EOL
      - name: Upload PR Number as Artifact
        if: github.event_name == 'pull_request' && matrix.offset == 1
        uses: actions/upload-artifact@v3
        with:
          name: pr_info.zip
          path: /tmp/pr
          retention-days: 30
